language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
addons:
  ssh_known_hosts: pajowu.de
before_install:
- openssl aes-256-cbc -K $encrypted_f34328c04a8c_key -iv $encrypted_f34328c04a8c_iv
  -in ssh_key.enc -out .travis/ssh_key -d
- openssl aes-256-cbc -K $encrypted_f34328c04a8c_key -iv $encrypted_f34328c04a8c_iv
  -in ssh_key.pub.enc -out .travis/ssh_key.pub -d
- openssl aes-256-cbc -K $encrypted_f34328c04a8c_key -iv $encrypted_f34328c04a8c_iv
  -in config.properties.enc -out config.properties -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/ssh_key
- ssh-add .travis/ssh_key
- scp -rp ~/clone/* pajowu@pajowu.de:travis/
script:
- gradle build
